# Generated by Django 4.1.3 on 2024-05-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nomeCliente',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
