# Generated by Django 4.1.3 on 2024-04-29 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Despesas',
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipoDespesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='despesa.tipodespesa')),
            ],
            options={
                'verbose_name_plural': 'Despesas',
            },
        ),
    ]
