# Generated by Django 4.1.3 on 2024-05-07 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recebimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recebimentos',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
